name: Build KeyCastOW

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: ilammy/msvc-dev-cmd@v1

    - name: Build Win32
      run: msbuild keycastow.vcxproj /p:Configuration=Release /p:Platform=Win32

    - uses: actions/upload-artifact@v4
      with:
        name: KeyCastOW
        path: Release/keycastow.exe
